### ISSUE TITLE
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

### ISSUE THREAD

**Issue by sijpkes** [open-craft/dalite-ng#63]
I'm not familiar with Django and attempting to install this on a CentOS server. 

Any insights on this error?

**Comment by sijpkes** [comment]
For reference:
`$ touch tools/local_settings.py`

Edit the file and add:
`SECRET_KEY = 'your secret key here'`

If this could be added to the docs for other users of this software, that would be fantastic!

**Comment by bradenmacdonald** [comment]
The README does say "Generate a secret key, e.g. using tools/gen_secret_key.py, an put it in dalite/local_settings.py." in the development setup instructions - is that sufficient?

**Comment by sijpkes** [comment]
Not if you're not familiar with Django.  For someone who works across many languages and frameworks, it's handy to have a clear go to. In my work I will go from Python/Django to PHP/Symphony to Ruby/Rails to Node.js and may never look at Python again for another 6 months, so having a note like above in the docs is always a massive time saver compared to having to look up the documentation to remember how to do something annoyingly simple.

**Comment by antoviaque** [comment]
@sijpkes Yup, I see what you mean - would you want to suggest the exact formulation that would have been the most useful to you? For documentation you can even post the PR directly from the web interface, ie at https://github.com/open-craft/dalite-ng/edit/master/README.md
