### ISSUE TITLE
OAuth 1.0 request in Blackboard

### ISSUE THREAD

**Issue by sijpkes** [open-craft/dalite-ng#64]
I'm trying to setup Dalite with Blackboard and am getting this.  I've built other LTI tools and suspect it may be the way Blackboard is building the signature or dalite only supports oAuth 2.0, which would be a show stopper. 

`Invalid LTI Request: Invalid signature. Expected signature base string: POST& ...` I've suppressed further output as this is a private server.

**Comment by sijpkes** [comment]
I've set this dalite up again and am accessing via mod_wsgi in apache. I am now getting a different error on the other server which is a vagrant box.

```
AttributeError at /lti/
'AnonymousUser' object has no attribute '_meta'
Request Method:	POST
Request URL:	http://localhost:8080/dalite-ng/lti/
Django Version:	1.8.17
Exception Type:	AttributeError
Exception Value:	
'AnonymousUser' object has no attribute '_meta'
Exception Location:	/usr/local/lib/python2.7/site-packages/django/utils/functional.py in inner, line 226
Python Executable:	/usr/bin/python
Python Version:	2.7.12
Python Path:	
['/var/www/dalite-ng',
 '/usr/local/lib/python27.zip',
 '/usr/local/lib/python2.7',
 '/usr/local/lib/python2.7/plat-linux2',
 '/usr/local/lib/python2.7/lib-tk',
 '/usr/local/lib/python2.7/lib-old',
 '/usr/local/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/site-packages',
 '/var/www/dalite-ng/src/httplib2/python2',
 '/var/www/dalite-ng/src/sanity-checker/files',
 '/var/www/dalite-ng/src/ims-lti-py-develop',
 '/var/www/dalite-ng/src/django-lti-tool-provider-master',
 '/var/www/dalite-ng/src/opaque-keys']
```

It traces to around line 111:
`/var/www/dalite-ng/dalite/__init__.py in authentication_hook`
 `login(request, user) `

It seems that in this case the user is not authenticating at all and the auto generated LTI username is not getting created with `User.objects.create_user`...

I've looked at the code and can see the django_lti_tool_provider authentication is using LTI 1.0, so this should not be causing the issue.

**Comment by sijpkes** [comment]
Solution: the development version of Blackboard Learn has a bug which does not pass the user roles with the LTI request.  This can be fixed by replacing at around line 157 in dalite/__init__.py:

Replace:
```
user_roles = set(extra_params.get("roles", set()))
```

With:
```
try:
            user_roles = set(extra_params.get("roles", set()))
        except TypeError as e:
            user_roles = "Learner";
            logger.info("TypeError when attempting to fetch user roles. Are you accesing from the Blackboard dev version? Defaulted to Learner as role.")
```

**Comment by antoviaque** [comment]
@sijpkes Glad you were able to sort out the issue already! And thanks for posting the solution, it will likely be useful to others. If you submit it as a PR with a test, we can actualy review it for a merge here -- it will likely be easier for you to keep upgrading dalite to new versions if you don't have code drift locally.

CC @bradenmacdonald

**Comment by sijpkes** [comment]
Thanks @antoviaque, I'll submit the PR when I have some time.  I've forked for the time being to continue working on this problem. The first part of this issue is still not resolved, I can launch from the dev server but when deployed as WSGI application on Apache I'm still getting:
```
Invalid LTI Request: Invalid signature. Expected signature base string:
```
I suspect it has something to do with the request being 'corrupted' by WSGI, i.e. it's not a clean UTF-8 string when passed to the oAuth class.

**Comment by sijpkes** [comment]
Thanks for your feedback @bradenmacdonald and @antoviaque.  I've forked this repo and created one with requirements for setting up on with `mod_wsgi` on apache behind a reverse proxy. 

I hope this will save others some headaches!

https://github.com/sijpkes/dalite-ng

**Comment by antoviaque** [comment]
@sijpkes Thank you!
